version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=src/app.py
    volumes:
      - .:/app
    env_file:
      - .env  # Carrega as variáveis do .env para a aplicação
    depends_on:
      - db    # Garante que o banco suba antes da aplicação
  db:
    image: postgres:13-alpine # Usando uma imagem oficial do Postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres_data: