version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=src/app.py
    volumes:
      - ./src:/app/src
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_PASS=123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db_data: