services:
  # backend:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_DEBUG=1
  #     - FLASK_APP=src/app.py
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env  # Carrega as variáveis do .env para a aplicação
  #   depends_on:
  #     - db    # Garante que o banco suba antes da aplicaçã
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: