"""Adiciona a tabela de produtos

Revision ID: 23d6ac8417d6
Revises: bd1e6d0e4feb
Create Date: 2025-10-16 02:21:45.053880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d6ac8417d6'
down_revision = 'bd1e6d0e4feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('cd_product', sa.UUID(), nullable=False),
    sa.Column('ds_product_name', sa.String(length=255), nullable=False),
    sa.Column('ds_product_description', sa.Text(), nullable=True),
    sa.Column('vr_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_product_type', sa.Enum('PRODUTO', 'SERVICO', name='producttype'), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cd_product')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_ds_product_name'), ['ds_product_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_ds_product_name'))

    op.drop_table('product')
    # ### end Alembic commands ###
