"""Initial migration with SQLite

Revision ID: 5e252070ead8
Revises: 
Create Date: 2025-09-04 00:26:31.669219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e252070ead8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('cd_user', sa.String(length=36), nullable=False),
    sa.Column('ds_user', sa.String(length=255), nullable=False),
    sa.Column('ds_user_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dt_user_createdat', sa.DateTime(), nullable=False),
    sa.Column('dt_user_last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cd_user'),
    sa.UniqueConstraint('ds_user_email')
    )
    op.create_table('transaction',
    sa.Column('cd_transaction', sa.String(length=36), nullable=False),
    sa.Column('vr_transaction', sa.Float(), nullable=False),
    sa.Column('id_transaction_type', sa.Integer(), nullable=False),
    sa.Column('dt_transaction', sa.Date(), nullable=False),
    sa.Column('dt_transaction_created', sa.DateTime(), nullable=False),
    sa.Column('cd_user', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cd_user'], ['user.cd_user'], ),
    sa.PrimaryKeyConstraint('cd_transaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    # ### end Alembic commands ###
