"""Criação inicial das tabelas com enums corretos

Revision ID: 8173d78f0573
Revises: 
Create Date: 2025-10-16 03:13:51.292939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8173d78f0573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.Column('ds_customer_name', sa.String(length=255), nullable=False),
    sa.Column('ds_customer_email', sa.String(length=255), nullable=False),
    sa.Column('ds_customer_phone', sa.String(length=20), nullable=True),
    sa.Column('ds_customer_cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('ds_customer_address', sa.String(length=500), nullable=True),
    sa.Column('ds_customer_city', sa.String(length=100), nullable=True),
    sa.Column('ds_customer_state', sa.String(length=2), nullable=True),
    sa.Column('ds_customer_zip_code', sa.String(length=10), nullable=True),
    sa.Column('ds_customer_country', sa.String(length=100), nullable=True),
    sa.Column('dt_customer_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_customer_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_customer_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cd_customer'),
    sa.UniqueConstraint('ds_customer_cpf_cnpj'),
    sa.UniqueConstraint('ds_customer_email')
    )
    op.create_table('product',
    sa.Column('cd_product', sa.UUID(), nullable=False),
    sa.Column('ds_product_name', sa.String(length=255), nullable=False),
    sa.Column('ds_product_description', sa.Text(), nullable=True),
    sa.Column('vr_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_product_type', sa.Enum('produto', 'servico', name='producttype'), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cd_product')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_ds_product_name'), ['ds_product_name'], unique=True)

    op.create_table('user',
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('ds_user', sa.String(length=255), nullable=False),
    sa.Column('ds_user_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dt_user_createdat', sa.DateTime(), nullable=False),
    sa.Column('dt_user_last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cd_user'),
    sa.UniqueConstraint('ds_user_email')
    )
    op.create_table('interaction',
    sa.Column('cd_interaction', sa.UUID(), nullable=False),
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('ds_notes', sa.Text(), nullable=False),
    sa.Column('id_interaction_type', sa.Enum('VENDA', 'LIGACAO', 'EMAIL', 'REUNIAO', 'CONTATO', name='interactiontype'), nullable=False),
    sa.Column('dt_interaction', sa.DateTime(), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cd_customer'], ['customer.cd_customer'], ),
    sa.ForeignKeyConstraint(['cd_user'], ['user.cd_user'], ),
    sa.PrimaryKeyConstraint('cd_interaction')
    )
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_cd_customer'), ['cd_customer'], unique=False)

    op.create_table('transaction',
    sa.Column('cd_transaction', sa.UUID(), nullable=False),
    sa.Column('vr_transaction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_transaction_type', sa.Enum('ENTRADA', 'SAIDA', name='transactiontype'), nullable=False),
    sa.Column('dt_transaction', sa.Date(), nullable=False),
    sa.Column('dt_transaction_created', sa.DateTime(), nullable=False),
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cd_customer'], ['customer.cd_customer'], ),
    sa.ForeignKeyConstraint(['cd_user'], ['user.cd_user'], ),
    sa.PrimaryKeyConstraint('cd_transaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_cd_customer'))

    op.drop_table('interaction')
    op.drop_table('user')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_ds_product_name'))

    op.drop_table('product')
    op.drop_table('customer')
    # ### end Alembic commands ###
