"""Adiciona a tabela de interações

Revision ID: 9d49d36c4b49
Revises: 23d6ac8417d6
Create Date: 2025-10-16 02:34:46.214749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d49d36c4b49'
down_revision = '23d6ac8417d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('cd_interaction', sa.UUID(), nullable=False),
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('ds_notes', sa.Text(), nullable=False),
    sa.Column('id_interaction_type', sa.Enum('VENDA', 'LIGACAO', 'EMAIL', 'REUNIAO', 'CONTATO', name='interactiontype'), nullable=False),
    sa.Column('dt_interaction', sa.DateTime(), nullable=False),
    sa.Column('dt_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cd_customer'], ['customer.cd_customer'], ),
    sa.ForeignKeyConstraint(['cd_user'], ['user.cd_user'], ),
    sa.PrimaryKeyConstraint('cd_interaction')
    )
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interaction_cd_customer'), ['cd_customer'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interaction_cd_customer'))

    op.drop_table('interaction')
    # ### end Alembic commands ###
