"""Initial migration

Revision ID: afd0a79467a9
Revises: 
Create Date: 2025-09-01 23:49:28.172283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afd0a79467a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('cd_role', sa.Integer(), nullable=False),
    sa.Column('ds_role', sa.String(length=80), nullable=False),
    sa.Column('ds_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cd_role'),
    sa.UniqueConstraint('ds_role')
    )
    op.create_table('users',
    sa.Column('cd_user', sa.Integer(), nullable=False),
    sa.Column('ds_user', sa.String(length=100), nullable=False),
    sa.Column('ds_user_email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('dt_user_nasc', sa.Date(), nullable=False),
    sa.Column('dt_user_create', sa.DateTime(), nullable=True),
    sa.Column('cd_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cd_role'], ['roles.cd_role'], ),
    sa.PrimaryKeyConstraint('cd_user'),
    sa.UniqueConstraint('ds_user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
