"""Criação inicial das tabelas com tipos corretos

Revision ID: bd1e6d0e4feb
Revises: 
Create Date: 2025-10-16 01:41:35.801259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1e6d0e4feb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.Column('ds_customer_name', sa.String(length=255), nullable=False),
    sa.Column('ds_customer_email', sa.String(length=255), nullable=False),
    sa.Column('ds_customer_phone', sa.String(length=20), nullable=True),
    sa.Column('ds_customer_cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('ds_customer_address', sa.String(length=500), nullable=True),
    sa.Column('ds_customer_city', sa.String(length=100), nullable=True),
    sa.Column('ds_customer_state', sa.String(length=2), nullable=True),
    sa.Column('ds_customer_zip_code', sa.String(length=10), nullable=True),
    sa.Column('ds_customer_country', sa.String(length=100), nullable=True),
    sa.Column('dt_customer_created_at', sa.DateTime(), nullable=False),
    sa.Column('dt_customer_updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_customer_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('cd_customer'),
    sa.UniqueConstraint('ds_customer_cpf_cnpj'),
    sa.UniqueConstraint('ds_customer_email')
    )
    op.create_table('user',
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('ds_user', sa.String(length=255), nullable=False),
    sa.Column('ds_user_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('dt_user_createdat', sa.DateTime(), nullable=False),
    sa.Column('dt_user_last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cd_user'),
    sa.UniqueConstraint('ds_user_email')
    )
    op.create_table('transaction',
    sa.Column('cd_transaction', sa.UUID(), nullable=False),
    sa.Column('vr_transaction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_transaction_type', sa.Enum('ENTRADA', 'SAIDA', name='transactiontype'), nullable=False),
    sa.Column('dt_transaction', sa.Date(), nullable=False),
    sa.Column('dt_transaction_created', sa.DateTime(), nullable=False),
    sa.Column('cd_user', sa.UUID(), nullable=False),
    sa.Column('cd_customer', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cd_customer'], ['customer.cd_customer'], ),
    sa.ForeignKeyConstraint(['cd_user'], ['user.cd_user'], ),
    sa.PrimaryKeyConstraint('cd_transaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('customer')
    # ### end Alembic commands ###
